/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ScanHeader {
  format: "kqk";
  format_version: 1;
  skeleton: "kq-skel-v1";
  scan_id: string;
  pose_model: PoseModel;
  device: Device;
  camera: Camera;
  battery: Battery;
  segment: Segment;
  frame_count: number;
  started_at: string;
}
export interface PoseModel {
  id: string;
  version: string;
  runtime: "tflite" | "coreml" | "onnx" | "mediapipe" | "tensorrt";
}
export interface Device {
  platform: "ios" | "android" | "web" | "edge";
  model: string;
  app_version: string;
}
export interface Camera {
  fps: number;
  width: number;
  height: number;
  orientation: "portrait" | "landscape";
  height_m: number | null;
}
export interface Battery {
  id: string;
  version: string;
}
export interface Segment {
  kind: "assessment" | "exercise" | "test";
  code: string;
}
