// Generated by packages/contracts/build.py from kinetiq_contracts. Do not edit.

export const SKELETON_VERSION = "kq-skel-v1";

export const JOINTS = [
  "pelvis",
  "left_hip",
  "right_hip",
  "spine_mid",
  "chest",
  "neck",
  "head",
  "left_shoulder",
  "right_shoulder",
  "left_elbow",
  "right_elbow",
  "left_wrist",
  "right_wrist",
  "left_knee",
  "right_knee",
  "left_ankle",
  "right_ankle",
  "left_heel",
  "right_heel",
  "left_foot_index",
  "right_foot_index",
] as const;

export type Joint = (typeof JOINTS)[number];

export const JOINT_COUNT = 21;

/** Bytes per frame: int32 t_ms + JOINT_COUNT × 4 float32. */
export const FRAME_BYTES = 340;
