"""Regenerate what is derived from the Pydantic models: the JSON Schema and the TS types.

Run after any change to `src/kinetiq_contracts`:

    uv run python packages/contracts/build.py
"""

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

from pydantic.json_schema import GenerateJsonSchema

from kinetiq_contracts import FRAME_BYTES, JOINT_COUNT, JOINTS, SKELETON_VERSION, ScanHeader

ROOT = Path(__file__).parent
SCHEMA_PATH = ROOT / "schema" / "scan-header.schema.json"
TS_SRC = ROOT / "ts" / "src"


class _NoFieldTitles(GenerateJsonSchema):
    """Leave titles off fields so the TS generator inlines their types instead of aliasing each."""

    def field_title_should_be_set(self, schema: Any) -> bool:
        return False


def header_schema_json() -> str:
    schema = ScanHeader.model_json_schema(schema_generator=_NoFieldTitles)
    return json.dumps(schema, indent=2) + "\n"


def skeleton_ts() -> str:
    joints = "\n".join(f'  "{name}",' for name in JOINTS)
    return (
        "// Generated by packages/contracts/build.py from kinetiq_contracts. Do not edit.\n\n"
        f'export const SKELETON_VERSION = "{SKELETON_VERSION}";\n\n'
        f"export const JOINTS = [\n{joints}\n] as const;\n\n"
        "export type Joint = (typeof JOINTS)[number];\n\n"
        f"export const JOINT_COUNT = {JOINT_COUNT};\n\n"
        "/** Bytes per frame: int32 t_ms + JOINT_COUNT × 4 float32. */\n"
        f"export const FRAME_BYTES = {FRAME_BYTES};\n"
    )


def main() -> None:
    SCHEMA_PATH.parent.mkdir(exist_ok=True)
    SCHEMA_PATH.write_text(header_schema_json(), encoding="utf-8", newline="\n")
    (TS_SRC / "skeleton.generated.ts").write_text(skeleton_ts(), encoding="utf-8", newline="\n")

    pnpm = shutil.which("pnpm")
    if pnpm is None:
        raise SystemExit("pnpm not found; it is needed to generate the TS header types")
    subprocess.run(
        [
            pnpm,
            "exec",
            "json2ts",
            "--input",
            str(SCHEMA_PATH),
            "--output",
            str(TS_SRC / "header.generated.ts"),
        ],
        cwd=ROOT,
        check=True,
    )


if __name__ == "__main__":
    main()
